name: ghcr.io container cleanup
description: Remove old and untagged images from the ghcr.io container registry

inputs:
  package-owner:
    description: Organization/Owner for the package
    required: true
    type: string
    default: ${{ github.actor }}
  package-name:
    description: Name of the package
    required: true
    type: string
  keep-versions:
    description: Number of package versions to keep
    required: true
    type: string
    default: 5
  token:
    description: GitHub PAT to perform API calls
    required: true
    type: string
  delete-orphans:
    description: Delete versions which are not tagged
    required: true
    type: boolean
    default: false
  dry-run:
    description: Don't perform DELETE API calls
    required: true
    type: boolean
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PACKAGE_OWNER: ${{ inputs.package-owner }}
    PACKAGE_NAME: ${{ inputs.package-name }}
    KEEP_VERSIONS: ${{ inputs.keep-versions }}
    TOKEN: ${{ inputs.token }}
    DELETE_ORPHANS: ${{ inputs.delete_orphans && '1' || '0' }}
    DRY_RUN: ${{ inputs.dry-run && '1' || '0' }}
